---
- name: 플레이북
  hosts: all
  become: yes
  tasks: 
    - name: httpd installation
      yum: 
        name: httpd
        state: present

    - name: start get_url
      get_url: url=https://www.naver.com dest=/var/www/html

    - name: stop firewalld
      service: 
        name: firewalld
        state: stopped
        enabled: false

    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: true
